spring.application.name=gateway
server.port=8080

logging.level.com.chefit.gateway=DEBUG
logging.level.org.springframework.web=INFO

logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5p) %clr([%t]){faint} %clr(%logger{36}){cyan} - %m%n
