spring.application.name=auth
server.port=8082
spring.docker.compose.enabled=false

logging.file.name=logs/auth.log
logging.level.com.chefit.auth=DEBUG
logging.level.org.springframework.web=INFO

logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5p) %clr([%t]){faint} %clr(%logger{36}){cyan} - %m%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%t] %logger{36} - %m%n
